FROM php:8.1-apache

RUN apt-get update && apt-get install -y \
    libzip-dev zip unzip git && \
    docker-php-ext-install mysqli pdo pdo_mysql && \
    a2enmod rewrite && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR /var/www/html

COPY . /var/www/html

RUN chown -R www-data:www-data /var/www/html

EXPOSE 80

CMD ["apache2-foreground"]
